# Generated by Django 3.1.7 on 2021-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('times_available', models.CharField(default='N/A', max_length=300)),
                ('phone_number', models.IntegerField(default=-1)),
            ],
        ),
    ]
