# Generated by Django 3.1.7 on 2021-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210319_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='phone_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='times_available',
            field=models.CharField(default='N/A', max_length=300),
        ),
    ]
