# Generated by Django 3.1.7 on 2021-03-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210319_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='times_available',
            field=models.CharField(max_length=300),
        ),
    ]
