# Generated by Django 3.1.7 on 2021-03-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210319_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='times_available',
            field=models.TextField(max_length=300),
        ),
    ]
